if(NOT SHADER_FILES)
  message(FATAL_ERROR "EmbedShaders.cmake: SHADER_FILES is not set")
endif()
if(NOT OUT_FILE)
  message(FATAL_ERROR "EmbedShaders.cmake: OUT_FILE is not set")
endif()
set(
  CONTENT
  "#pragma once
// Auto-generated by cmake/EmbedShaders.cmake from engine/src/shader/*.{vert,frag,comp,hlsl} -- do not edit by hand. Edit the real shader source files and rebuild to regenerate this.
#include <string_view>
namespace kuki::embedded_shader {
"
)
foreach(SHADER_FILE ${SHADER_FILES})
  file(READ "${SHADER_FILE}" FILE_CONTENT)
  get_filename_component(FILE_NAME "${SHADER_FILE}" NAME)
  string(MAKE_C_IDENTIFIER "${FILE_NAME}" VAR_NAME)
  string(
    APPEND CONTENT
    "inline constexpr std::string_view ${VAR_NAME} = R\"KUKI_SHADER_SRC(${FILE_CONTENT})KUKI_SHADER_SRC\";\n"
  )
endforeach()
string(APPEND CONTENT "} // namespace kuki::embedded_shader\n")
file(WRITE "${OUT_FILE}" "${CONTENT}")
