name: CMake
on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
jobs:
  cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
            cpack_generator: DEB
          - os: windows-latest
            cc: cl
            cxx: cl
            cpack_generator: NSIS
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"
      - name: Install required packages
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential clang cmake libgl1-mesa-dev ninja-build xorg-dev
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - name: Install Ninja build
        if: runner.os == 'Windows'
        run: winget install --id Ninja-build.Ninja --accept-source-agreements --disable-interactivity
      - uses: actions/cache@v5
        with:
          path: build
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt','**/CMakePresets.json') }}
          restore-keys: |
            ${{ runner.os }}-cmake-
      - name: CMake configure
        run: cmake -G "Ninja" --preset Release -DKUKI_BUILD_TESTS=ON
      - name: CMake build
        run: cmake --build --preset Release
      - name: CTest
        run: ctest --preset Release --output-on-failure
      - name: CPack
        if: startsWith(github.ref, 'refs/tags/')
        run: cpack -G ${{ matrix.cpack_generator }} --preset Release
      - uses: actions/upload-artifact@v7
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: installer-${{ matrix.os }}
          path: |
            build/*.exe
            build/*.deb
